FROM python:3.12-slim


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Make use of virtualenv, to cleanly install Python requirements, without
# triggering the ugly "WARNING: Running pip as the 'root' user can result
# in broken permissions and conflicting behaviour".
ENV VIRTUAL_ENV=/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN python3 -m venv $VIRTUAL_ENV

# Install requirements
RUN apt update && apt install -y \
    make

COPY requirements/requirements.txt /tmp
RUN python3 -m pip install -r /tmp/requirements.txt

USER 1000:1000

# Create the path where the code must be mounted
WORKDIR /code
ENV PYTHONPATH /code

CMD ["/bin/bash"]
