---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.12

repos:

  # Upgrades various code constructs to constructs that are
  # supported by newer versions of Python.
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus

  # Applies code formatting.
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        files: ^(src|tests)/.+\.py$

  # Makes imports absolute (as recommended by PEP8)
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  # Sorts include headers in a standard way.
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  # Checks code style.
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^(src|tests)/.+\.py$

  # Checks typing hints. Strict checking is disabled here, but it is
  # enabled in the tox configuration. This is just a first line of
  # defense. Also, strict checking would be run for tests too here,
  # and that would yield way too many unneeded issues.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        pass_filenames: true
        additional_dependencies:
          - coloredlogs
          - pytest
          - types-psycopg2
          - click
          - requests
          - types-requests

  # Commits must be handled through merge requests.
  # Therefore, committing directly to the main branch is not allowed.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args:
          - --branch=main
