name: canvas-cursusverloop
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        healthcheck:
            test: rabbitmq-diagnostics status
            interval: 4s
            timeout: 4s
            retries: 10
        ports:
            - 5672:5672
            - 15672:15672
    cursusverloop:
        container_name: cursusverloop
        build:
            dockerfile: docker/deployment/Containerfile
        ports:
            - 8083:8083/tcp
        volumes:
            - ./:/code
        depends_on:
            rabbitmq:
             condition: service_healthy
        restart: "no"
        command: bash -c "./bin/canvasctl run webserver"
