[tool.black]
target-version = ['py312']
line-length = 100

[tool.pytest.ini_options]
testpaths = [ "tests/" ]
pythonpath = "src/"
addopts = "--tb=short -q"

[tool.isort]
profile = "black"
src_paths = ["src/", "tests/"]
line_length = 100

[tool.mypy]
python_version = "3.12"
strict = true
check_untyped_defs = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.pydeps]
reverse = true
rankdir = "BT"

[tool.coverage.run]
relative_files = true
source = [ "src/" ]
branch = true
omit = [
    "src/cli_app/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@(abc\\.)?abstractmethod",
    "@unittest\\.skip",
    "raise NotImplementedError",
]
